tmgmt.translator.settings.globalsight:
  type: mapping
  mapping:
    auto_accept:
      type: boolean
      label: Automatically accept
    endpoint:
      type: string
      label: Webservice Endpoint URL.
    username:
      type: string
      label: GlobalSight username.
    password:
      type: string
      label: GlobalSight password.
    proxyhost:
      type: string
      label: Proxy host.
    proxyport:
      type: string
      label: Proxy port.
    file_profile_id:
      type: string
      label: File profile ID.